config/routes.rb
TaskManager::Application.routes.draw do
  
  root :to => 'activities#index'

  get "login" => 'logins#new', :as => "login"
  post "login" => 'logins#create', :as => "create_login" 
  get 'logout' => 'logins#destroy', :as => 'logout'

  get "projects" => 'projects#index', :as => "projects"
  get "projects/new" => 'projects#new', :as => "new_project"

  get "projects/:name/edit" => 'projects#edit', :as => "edit_project"
  get "project/:name" => 'projects#show', :as => "project"

  post "projects" => 'projects#create' 
  put "project/:name" => 'projects#update'


  delete "projects/:name/delete" => 'projects#destroy', :as => "delete_project"
  get "project/:name" => 'projects#show', :as => "project"


  post "create_user" => 'users#create', :as => "create_user"
  get "signup" => 'users#new', :as => "signup"


  resources :users, :tasks, :tags, :comments
  resources :activities


end

app/models/task.rb
class Task < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  attr_accessible :description, :due_date, :name, :priority, :project_id, :tag_id, :user_id, :completed
  

  has_and_belongs_to_many :users

  has_and_belongs_to_many :tags
  belongs_to :project
  has_many :comments
  
  
  validates :name, :description, :project_id, :tag_id, :user_id, presence: true
  
  # def email_owner(current_user)
  #   Pony.mail({
  #             :to => "#{self.user.email}",
  #             :via => :smtp,
  #             :subject => "#{current_user.name}" + " has assigned you a task.",
  #             :body => "Your task is " + "#{self.name}" + ".",
  #             :via_options => {
  #               :address              => 'smtp.gmail.com',
  #               :port                 => '587',
  #               :enable_starttls_auto => true,
  #               :user_name            => 'taskinc.taskmanager@gmail.com',
  #               :password             => 'ocsbudai',
  #               :authentication       => :plain,
  #               :domain               => "localhost.localdomain"
  #
  #               }
  #             })
  # end
      
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  skip_before_filter :authorize, :only => [:index, :show]
 
  def index
    # @tasks = Task.all
    @tasks = Task.includes(:comments => :project).all
  end
  
  def find
    @task = Task.new
  end
  
  def new
    @task = Task.new
    @projects = Project.all
    @tags = Tag.all
    @users = User.all
  end
 
  def create
 
     @task = Task.new(params[:task])
    
     # TODO Figure out why this is here. 
     @task.project_id = (params[:task][:project_id]).to_i
     @task.tag_id = (params[:task][:tag_id]).to_i
     @task.user_id = (params[:task][:user_id]).to_i
     @task.completed = (params[:task][:completed])
    
     @user = User.find(@task.user_id)
     if @task.save
       UserMailer.task(@user).deliver
                     @project = Project.find(@task.project_id)
             redirect_to project_path(@project.name), notice: "Your email notification to #{@user.name} was sent successfully."
            else
             render "new", alert: "Invalid. Your task was not added."
     end 
   end
    
  
  def edit
    @task = Task.find(params[:id])
  end
  
  def update
    @users = User.all
    @task = Task.find(params[:id])
    @user = User.find(@task.user_id)
    
    if @task.update_attributes(params[:task])
        UserMailer.update_task(@user).deliver
       @project = Project.find(@task.project_id)

      redirect_to project_path(@project.name), :notice => "Your email notification to #{@user.name} was sent successfully."
    else
      render "edit", alert: "Invalid. Your task was not updated."
    end
        
  end

  def destroy
    @task = Task.find(params[:id])
    @task.delete
    redirect_to tasks_path, :notice => "You have deleted this task."
  end

  
  def show
    @task = Task.find(params[:id])
    @project = Project.find(@task.project_id)
    @tag = Tag.find(@task.tag_id)
    @comments = Comment.new
    @user = User.find(@task.user_id)
    
    if @task.completed
      @response = "Yes! Good work!"
    else
      @response = "No"
    end
  end
  
  
  
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/delete.html.erb
TASKS DELETE

app/views/tasks/edit.html.erb
<div id="container">
  <div id="header">
    <div id="headerguts">
    	<h1>Task, Inc.</h1>
  	</div>
  </div>
	
  <div id="sidebar">
    <div id="sidebarguts">
    	<h2>Edit Task</h2>
	    <div id="sidebarindent">
		   	 	 <%= link_to("Cancel Edit", tasks_path) %></p>
		    <p><%= link_to("Return to Home", root_path) %></p>
	  	</div>
 	 	</div>
  </div>
	
    <div id="contentbig">
      <div id="contentbigguts">
    		<div id="contentbigguts">
					
     		 	<%= form_for @task do |t| %>
        <p>
          <%= t.label :name %>
          <%= t.text_field :name %>
        </p>

      	<p>
          <%= t.label :description %>
          <%= t.text_field :description %>
        </p>

      	<p>
          <%= t.label :priority %>
          <%= t.text_field :priority %>
        </p>

      	<p>
          <%= t.label :due_date %>
          <%= t.text_field :due_date %>
        </p>

        <p>
          <%= t.label :project %>
          <%= t.collection_select :project_id, Project.all, :id, :name %>
        </p>
				
        <p>
          <%= t.label :tag %>
          <%= t.collection_select :tag_id, Tag.all, :id, :name %>
        </p>
				
        <p>
          <%= t.label :assigned_to %>
          <%= t.collection_select :user_id, User.all, :id, :name %>
        </p>
				
			 	<p>
					<%= t.label :completed %>
					<%= t.check_box :completed%>
				</p>

					<%= t.submit value: "Save Changes"%>
					
					<% end %>
      
   		</div>
  	</div>
	</div>
	
	<div id="clearcontentright">
	</div>
	
	<div id="footer">
	</div>
  
</div>

app/views/tasks/index.html.erb
<div id="container">
  <div id="header">
    <div id="headerguts">
    	<h1>Task, Inc.</h1>
  	</div>
  </div>
  <div id="sidebar">
    <div id="sidebarguts">
    	<h2>Tasks Index</h2>
		    <div id="sidebarindent">
		    	<p><%= link_to("Create a New Task", new_task_path) %></p>
		    	<p><%= link_to("Return to Home", root_path) %></p>
		  	</div>
  	</div>
  </div>
	
    <div id="contentbig">
      <div id="contentbigguts">
    		<div id="contentbigguts">
      
      		<p>
      				<% @tasks.each do |task|%>

      		<p><%= link_to(task.name, task_path(task.id)) %></p>
     		 		<%end%>
     		 	</p>
    		</div>
  		</div>
    </div>
		
  <div id="clearcontentright">
  </div>
	
  <div id="footer">
  </div>
  
</div>

app/views/tasks/new.html.erb
<div id="container">
	
  <div id="header">
    <div id="headerguts">
    	<h1>Task, Inc.</h1>
  	</div>
  </div>
	
  <div id="sidebar">
    <div id="sidebarguts">
    	<h2>New Task</h2>
    		<div id="sidebarindent">
    			<p><%= link_to("Cancel Create", tasks_path)%>
    			<p><%= link_to("Return to Home", root_path) %></p>
  			</div>
  	</div>
  </div>
	
	<div id="contentbig">
	  <div id="contentbigguts">  
			<div id="contentbigguts">
			
	        <%= form_for @task do |t| %>

	      <p>
	        <%= t.label :name %>
	        <%= t.text_field :name %>
	      </p>
			
	      <p>
	        <%= t.label :description %>
	        <%= t.text_field :description %>
	      </p>
			
	      <p>
	        <%= t.label :priority %>
	        <%= t.text_field :priority %>
	      </p>
			 
	   	 	<p>
	        <%= t.label :due_date %>
	        <%= t.text_field :due_date %>
	      </p>

	      <p>
	        <%= t.label :project %>
	        <%= t.collection_select :project_id, Project.all, :id, :name %>
	      </p>
			
	      <p>
	        <%= t.label :tag %>
	        <%= t.collection_select :tag_id, Tag.all, :id, :name %>
	      </p>
			
	    	<p>
	        <%= t.label :assigned_to %>
	        <%= t.collection_select :user_id, User.all, :id, :name %>
	      </p>
			
	    	<p>
	        <%= t.label :completed %>
	        <%= t.check_box :completed%>
	      </p>
			
	      <p> 
	        <%= t.submit value: "Create Task" %>

	      	<% end %>
				</p>   
	  		</p>
			</div>
	 	</div>
	</div>
		
	<div id="clearcontentright">
	</div>
	
	<div id="footer">
	</div>
  
</div>

app/views/tasks/show.html.erb
<div id="container">
	
  <div id="header">
    <div id="headerguts">
    	<h1>Task, Inc.</h1>
  	</div>
  </div>
	
  <div id="sidebar">
    <div id="sidebarguts">
    	<h2>Task Details</h2>
		    <div id="sidebarindent">
			    <p><%= link_to("Return to Projects", projects_path) %></p>
			    <p><%= link_to("Edit this Task", edit_task_path) %></p>
			    <p><%= link_to("Delete this Task", task_path, :method => :delete) %></p>  
			    <p><%= link_to("Create a New Task", new_task_path) %></p>
			    <p><%= link_to("Return to Task Index", tasks_path) %></p>
			    <p><%= link_to("Return to Home", root_path) %></p>
		  	</div>
  	</div>
 	</div>

    <div id="contentleft">
      <div id="smallgutsl">
	    	<p>Name: <%= @task.name %></p>
	    	<p>Description: <%= @task.description %></p>
	    	<p>Priority: <%= @task.priority %></p>
	    	<p>Due Date: <%= @task.due_date %></p>
	      <p>Project: <%= @project.name %></p>
	      <p>Tag: <%= @tag.name %></p>
	      <p>Assigned To: <%= @user.name %> </p>
				<p>Completed? <%= @response %></p>
      </div>
    </div>
     
    <div id="contentright">
      <div id="smallgutsr">
      	<p>Add a comment to this task:</p>
	        <div id="smallindentr">
						
	    				 <% @task.comments.each do |c| %>

	        	<a><%= c.message %></a>
	          <a><%= link_to("Edit", edit_comment_path(c.id)) %></a>
	          <a><%= link_to("Delete", comment_path(c.id), :method => :delete) %></a><br/><br/>

	      			 <% end %>
    
		      		 <%= form_for @comments do |c| %>

	          <p><%= c.label :comment %></p>
	          <p><%= c.text_area :message %></p>

		           <%= c.hidden_field :user_id, { :value => current_user } %>
		           <%= c.hidden_field :task_id, { :value => @task.id } %>

		           <%= c.submit value: "Submit Comment" %>

		       		 <% end %>
		      </div>
      </div>
    </div>
		
	<div id="clearcontentright">
	</div>

	<div id="footer">
	</div>
  
</div>

app/views/tasks/update.html.erb
TASKS UPDATE