config/routes.rb
TaskManager::Application.routes.draw do
  
  root :to => 'activities#index'

  get "login" => 'logins#new', :as => "login"
  post "login" => 'logins#create', :as => "create_login" 
  get 'logout' => 'logins#destroy', :as => 'logout'

  get "projects" => 'projects#index', :as => "projects"
  get "projects/new" => 'projects#new', :as => "new_project"

  get "projects/:name/edit" => 'projects#edit', :as => "edit_project"
  get "project/:name" => 'projects#show', :as => "project"

  post "projects" => 'projects#create' 
  put "project/:name" => 'projects#update'


  delete "projects/:name/delete" => 'projects#destroy', :as => "delete_project"
  get "project/:name" => 'projects#show', :as => "project"


  post "create_user" => 'users#create', :as => "create_user"
  get "signup" => 'users#new', :as => "signup"


  resources :users, :tasks, :tags, :comments
  resources :activities


end

app/models/project.rb
class Project < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }
  
  attr_accessible :name, :desc
  
  has_many :tasks
  
  belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  skip_before_filter :authorize, :only => [:index, :show]
 
  def index
    @projects = Project.includes(:tasks => :project).all
  end
  
  def new
    @project = Project.new
  end
 
  def create
    @project = Project.new(params[:project])
    
    if @project.save
      redirect_to projects_path(@project.name), :notice => "You have saved a new project."
    else
      render "new"
    end
  end
  
  def edit
    @project = Project.find_by_name(params[:name])
  end
  
  def update
    @project = Project.find_by_name(params[:project][:name])
    
    if @project.update_attributes(params[:project])
      redirect_to project_path(@project.name), :notice => "You have upated this project."
    else
      render "edit"
    end
  end

  def destroy
    @project = Project.find_by_name(params[:name])
    @project.delete
    redirect_to projects_path, :notice => "You have deleted this project."
  end
  
  
  def show
    @project = Project.find_by_name(params[:name])
    @task = Task.new
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/delete.html.erb
PROJECTS DELETE

app/views/projects/edit.html.erb
<div id="container">
  <div id="header">
    <div id="headerguts">
    	<h1>Task, Inc.</h1>
  	</div>
  </div>
	
  <div id="sidebar">
    <div id="sidebarguts">
    	<h2>New Project</h2>
	  		<div id="sidebarindent">
			    <p><%= link_to("Cancel Edit", projects_path) %></p>
			    <p><%= link_to("Return to Home", root_path) %></p>
			 	</div>
 		</div>
  </div>
	
  <div id="contentbig">
    <div id="contentbigguts">

  		<div id="contentbigguts">
      		<%= form_for @project do |t| %>
        <p>
          <%= t.label :name %>
          <%= t.text_field :name %>
        </p>
        <p>
          <%= t.label :description %>
          <%= t.text_field :desc %>
        </p>
      		<%= t.submit value: "Save Changes" %>
					<% end %>
    	</div>	
			
		</div>
	</div>
	
	<div id="clearcontentright">
	</div>

	<div id="footer">
	</div>
</div>

app/views/projects/index.html.erb
<div id="container">
  <div id="header">
    <div id="headerguts">
    	<h1>Task, Inc.</h1>
  	</div>
  </div>
	
  <div id="sidebar">
    <div id="sidebarguts">
    	<h2>Projects Index</h2>
	    <div id="sidebarindent">
		    <p><%= link_to("Create a New Project", new_project_path) %></p>
		    <p><%= link_to("Return to Home", root_path) %></p>
		  </div>
  	</div>
  </div>
	
    <div id="contentbig">
      <div id="contentbigguts">
       
    		<div id="contentbigguts">
    					 <% @projects.each do |project|%>
    			<ul id="sortable">
    				<p><%= link_to(project.name, project_path(project.name)) %></p>
   				 		 <%end%>
    		</div>
  		</div>
    </div>
		
  <div id="clearcontentright">
  </div>
	
  <div id="footer">
  </div>
  
</div>

app/views/projects/new.html.erb
<div id="container">
  <div id="header">
    <div id="headerguts">
    	<h1>Task, Inc.</h1>
  	</div>
  </div>
	
  <div id="sidebar">
    <div id="sidebarguts">
    	<h2>New Project</h2>
			
		    <div id="sidebarindent">
			    <p><%= link_to("Cancel Create", projects_path)%>
			    <p><%= link_to("Return to Home", root_path) %></p>
			  </div>
  	</div>
  </div>
	
    <div id="contentbig">
      <div id="contentbigguts">   
		    <div id="contentbigguts">
	      		<%= form_for @project do |p| %>
	        <p>
	          <%= p.label :name %>
	          <%= p.text_field :name %>
	        </p>
	      	<p>
	          <%= p.label :description %>
	          <%= p.text_field :desc %>
	        </p>
	      		<%= p.submit value: "Create Project"%>

	     		 	<% end %>
		 		</div>
 		 	</div>
    </div>
		
	<div id="clearcontentright">
	</div>

	<div id="footer">
	</div>

</div>

app/views/projects/show.html.erb
<div id="container">
  <div id="header">
    <div id="headerguts">
    	<h1>Task, Inc.</h1>
  	</div>
  </div>
	
  <div id="sidebar">
	    <div id="sidebarguts">
	    	<h2>Project Details</h2>
	    <div id="sidebarindent">
		    <p><%= link_to("Edit this Project", edit_project_path) %></p>
		    <p><%= link_to("Delete this Project", delete_project_path, :method => :delete) %></p>  
		    <p><%= link_to("Create a New Project", new_project_path) %></p>
		    <p><%= link_to("Return to Project Index", projects_path) %></p>
		    <p><%= link_to("Return to Home", root_path) %></p>
	  	</div>
  	</div>
  </div>

    <div id="contentleft">
      <div id="smallgutsl">
	      <p>Name: <%= @project.name %></p> 
	      <p>Description: <%= @project.desc %></p>
	      <p>Tasks:</p>
	        <div id="smallindentl">	
	        		 <% @project.tasks.each do |t| %>
	          <p><%= link_to(t.name, task_path(t.id))%></p>
	        		 <% end %> 
        	</div>
      </div>
    </div>
     
    <div id="contentright">
      <div id="smallgutsr">
      	<p>Add a new task to this project:</p>
				
	        <div id="smallindentr">
	        		<%= form_for @task do |t| %>
	          <p>
	            <%= t.label :name %>
	            <%= t.text_field :name %>
	          </p>
	        	<p>
	            <%= t.label :description %>
	            <%= t.text_field :description %>
	        	</p>
	        	<p>
	            <%= t.label :priority %>
	            <%= t.text_field :priority %>
	          </p>
	        	<p>
	            <%= t.label :due_date %>
	            <%= t.text_field :due_date %>
	          </p>

	        	<p>
	            <%= t.label :project %>
	            <%= t.collection_select :project_id, Project.all, :id, :name %>
	          </p>
	        	<p>
	            <%= t.label :tag %>
	            <%= t.collection_select :tag_id, Tag.all, :id, :name %>
	          </p>
	        	<p>
	            <%= t.label :assigned_to %>
	            <%= t.collection_select :user_id, User.all, :id, :name %>
	          </p>
	          	<%= t.submit value: "Create Task" %>
	        		<% end %> 
	      </div>
				
	    </div>
    </div>
		
  <div id="clearcontentright">
  </div>

  <div id="footer">
  </div>
  
</div>

app/views/projects/update.html.erb
PROJECTS UPDATE