config/routes.rb
TaskManager::Application.routes.draw do
  
  root :to => 'activities#index'

  get "login" => 'logins#new', :as => "login"
  post "login" => 'logins#create', :as => "create_login" 
  get 'logout' => 'logins#destroy', :as => 'logout'

  get "projects" => 'projects#index', :as => "projects"
  get "projects/new" => 'projects#new', :as => "new_project"

  get "projects/:name/edit" => 'projects#edit', :as => "edit_project"
  get "project/:name" => 'projects#show', :as => "project"

  post "projects" => 'projects#create' 
  put "project/:name" => 'projects#update'


  delete "projects/:name/delete" => 'projects#destroy', :as => "delete_project"
  get "project/:name" => 'projects#show', :as => "project"


  post "create_user" => 'users#create', :as => "create_user"
  get "signup" => 'users#new', :as => "signup"


  resources :users, :tasks, :tags, :comments
  resources :activities


end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  
  has_and_belongs_to_many :tasks

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  skip_before_filter :authorize, :only => [:index, :show]

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(params[:tag])

    if @tag.save
      redirect_to tags_path(@tag.id), :notice => "You have saved a new tag."
    else
      render "new"
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])

    if @tag.update_attributes(params[:tag])
      redirect_to tags_path(@tag.id), :notice => "You have upated this tag."
    else
      render "edit"
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.delete
    redirect_to tags_path, :notice => "You have deleted this tag."

  end


  def show
    @tag = Tag.find(params[:id])
  end
  
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/delete.html.erb
TAGS DELETE

app/views/tags/edit.html.erb
<div id="container">
	
  <div id="header">
    <div id="headerguts">
    	<h1>Task, Inc.</h1>
  	</div>
  </div>
	
  <div id="sidebar">
    <div id="sidebarguts">
    	<h2>Edit Tag</h2>
		    <div id="sidebarindent">
		    	<p><%= link_to("Cancel Edit", tags_path) %></p>
		    	<p><%= link_to("Return to Home", root_path) %></p>
		  	</div>
  	</div>
  </div>
	
    <div id="contentbig">
      <div id="contentbigguts">
    		<div id="contentbigguts">
	      <p>
		      		<%= form_for @tag do |t| %>

		        <p>
		          <%= t.label :name %>
		          <%= t.text_field :name %>
		        </p>

		      		<%= t.submit value: "Save Changes"%>

		      		<% end %>		
    		</div>
 		 	</div>
    </div>
		
	<div id="clearcontentright">
	</div>
	
	<div id="footer">
	</div>
  
</div>

app/views/tags/index.html.erb
<div id="container">
  <div id="header">
    <div id="headerguts">
    	<h1>Task, Inc.</h1>
  	</div>
  </div>
	
  <div id="sidebar">
    <div id="sidebarguts">
   	 <h2>Tags Index</h2>
	    <div id="sidebarindent">
	    	<p><%= link_to("Create a New Tag", new_tag_path) %></p>
	    	<p><%= link_to("Return to Home", root_path) %></p>
	  	</div>
  	</div>
  </div>
	
    <div id="contentbig">
      <div id="contentbigguts">     
    		<div id="contentbigguts">
      
		   		<p>
		   			 <% @tags.each do |tag|%>

		    	<p><%= link_to(tag.name, tag_path(tag.id)) %></p>
		    		 <%end%>

   		 	</div>
 		 	</div>	
    </div>
		
	<div id="clearcontentright">
	</div>

	<div id="footer">
	</div> 
	
</div>

app/views/tags/new.html.erb
<div id="container">
  <div id="header">
    <div id="headerguts">
    	<h1>Task, Inc.</h1>
  	</div>
  </div>
	
  <div id="sidebar">
    <div id="sidebarguts">
    	<h2>New Tag</h2>
	    <div id="sidebarindent">
	    	<p><%= link_to("Cancel Create", tags_path)%>
	    	<p><%= link_to("Return to Home", root_path) %></p>
	  	</div>
 	 	</div>
  </div>
	
    <div id="contentbig">
      <div id="contentbigguts">
    		<div id="contentbigguts">
					
            		<%= form_for @tag do |t| %>
            <p> <%= t.label :name %>
                <%= t.text_field :name %>
            </p>
            		<%= t.submit value: "Create Tag"%>
								
           		 	<%end%>
     				</p>
   			</div>
			</div>
    </div>
		
	<div id="clearcontentright">
	</div>
	
	<div id="footer">
	</div>
  
</div>

app/views/tags/show.html.erb
<div id="container">
  <div id="header">
    <div id="headerguts">
    	<h1>Task, Inc.</h1>
  	</div>
  </div>
	
  <div id="sidebar">
    <div id="sidebarguts">
    	<h2>Tag Details</h2>
		    <div id="sidebarindent">
			    <p><%= link_to("Edit this Tag", edit_tag_path) %></p>
			    <p><%= link_to("Delete this Tag", tag_path, :method => :delete) %></p>  
			    <p><%= link_to("Create a New Tag", new_tag_path) %></p>
			    <p><%= link_to("Return to Tag Index", tags_path) %></p>
			    <p><%= link_to("Return to Home", root_path) %></p>
		  	</div>
  	</div>
 	 </div>
	 
    <div id="contentbig">
      <div id="contentbigguts">
    		<div id="contentbigguts">
    			<p>Name: <%= @tag.name %></p>
    		</div>	
 		 	</div>
    </div>
		
	<div id="clearcontentright">
	</div>

	<div id="footer">
	</div>
  
</div>

app/views/tags/update.html.erb
TAGS UPDATE