config/routes.rb
TaskManager::Application.routes.draw do
  
  root :to => 'activities#index'

  get "login" => 'logins#new', :as => "login"
  post "login" => 'logins#create', :as => "create_login" 
  get 'logout' => 'logins#destroy', :as => 'logout'

  get "projects" => 'projects#index', :as => "projects"
  get "projects/new" => 'projects#new', :as => "new_project"

  get "projects/:name/edit" => 'projects#edit', :as => "edit_project"
  get "project/:name" => 'projects#show', :as => "project"

  post "projects" => 'projects#create' 
  put "project/:name" => 'projects#update'


  delete "projects/:name/delete" => 'projects#destroy', :as => "delete_project"
  get "project/:name" => 'projects#show', :as => "project"


  post "create_user" => 'users#create', :as => "create_user"
  get "signup" => 'users#new', :as => "signup"


  resources :users, :tasks, :tags, :comments
  resources :activities


end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = PublicActivity::Activity.order("created_at desc")
 
  end
end


# @users = User.All
# @user.id = @task.user_id
#
# @user.id = @task.where(params[:task][:user_id])

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/index.html.erb
<div id="container">
  <div id="header">
    <div id="headerguts">
      <h1>Task, Inc.</h1>
    </div>
  </div>

  <div id="sidebar">
    <div id="sidebarguts">
      <h2>Home</h2>     
      <div id="sidebarindent">
        <p><%= link_to("Projects", projects_path)%></p>
        <p><%= link_to("Tasks", tasks_path)%></p>
        <p><%= link_to("Tags", tags_path)%></p>
        <p><%= link_to("Users", users_path)%></p>
        <p><%= link_to("Activity Feed", activities_path)%></p>
      </div>
    </div>
  </div>
  
  <div id="contentbig">
    <div id="contentbigguts">
    	<h2>Welcome to Task Manager!</h2>
    		<p>Please choose a link from the list on the left to interact with that module.</p>
    	<h3>Recent Activity</h3>	
			
	    <div id="contentbigguts">
	      <% @activities.each do |activity|%>
	        <div class="activity">
	          <%= activity.owner.name %>
	          <%= render_activity activity%>
	        </div> 
	      <% end %>
	    </div>
					
  	</div>
	</div>
	
  <div id="clearcontentright">
  </div>
		
  <div id="footer">
  </div>
  
</div>